# -*- coding: utf-8 -*-
"""bitirmeprojesi2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18xSrVlf4vO2FrhwCCLyXIpsGSmgERnNZ
"""

import  random as r
sayı = r.randint(3,100)
total = 0
deneme_sayisi = 0
print("Sayı Bilmece Oyununa Hoş Geldin sistem senin için 3-100 arasında sayı seçti sen ise 3 sayı tahmin ederek bulmaya çalışcaksın Hadi Bilmeceye Başlayalım ")

while True:
    for i in range(3):
        tahmin=int(input(f"{i+1}.sayıyı girin - "))
        total+=tahmin
    if total == sayı:
        print("TEBRİKLER SAYIYI BULDUNUZ")
        print(f"Yanlış yapılan deneme {deneme_sayısı}")
        98
        89

    else:
        print("Toplam sistemin sayısına eşit değil tekrar deneyelim ")
        deneme_sayisi += 1
        total=0
    if deneme_sayisi == 4:
        print(f"Joker kullanıldı !! {sayı+random.randint(2,8)} ile {sayı-random.randint(2,8)} arasında")
    if deneme_sayisi == 6:
        print(f"Bir Joker daha vereyim sana {sayı + random.randint(2,4)} ile {sayı - random.randint(2,4)} arasında")